language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm-3.3
  - hhvm-3.6
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer self-update
  - composer install --ignore-platform-reqs

notifications:
  email: change
